# fly.toml app configuration file generated for c3t-drop on 2024-12-22T11:26:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'c3t-drop'

[build]

[env]
EVENT_NAME = '38c3'
SCHEDULE_URLS = 'https://fahrplan.events.ccc.de/congress/2024/fahrplan/schedule/export/schedule.json,https://cfp.cccv.de/38c3-community-stages/schedule/export/schedule.json'

[[mounts]]
source = 'c3t_drop_files'
destination = '/app/files'
auto_extend_size_threshold = 80
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "100GB"

[http_service]
internal_port = 9000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
